name: ci
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [21.3, 22.2, 23]
        elixir: [1.8.2, 1.9.4, 1.10.4, 1.11.2]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix credo
      - run: mix format --check-formatted      
      - run: mix test
