name: ci
on: push



jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [22, 23, 24]
        elixir: ['1.11.4', '1.12', '1.13']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix do deps.get, deps.compile
      - run: mix credo
      - run: mix format --check-formatted
      - run: mix test
  dialyzer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [24]
        elixir: ['1.13']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - uses: actions/cache@v2
        id: mix-cache # id to use in retrieve action
        with:
          path: |
            _build
            deps
            priv/plts
          key: mix-cache-v0-${{matrix.elixir}}-${{matrix.otp}}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix do deps.get, deps.compile

      - run: mix dialyzer --halt-exit-status
